runtime: nodejs
env: flex
manual_scaling:
  instances: 1
network:
  session_affinity: true
handlers:
  - url: /
    static_dir: dist

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
